package com.jason.model;

import java.math.BigDecimal;
import java.util.Date;

public class HmUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.login_name
     *
     * @mbg.generated
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.user_token
     *
     * @mbg.generated
     */
    private String userToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.head_img
     *
     * @mbg.generated
     */
    private String headImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.point
     *
     * @mbg.generated
     */
    private BigDecimal point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.longitude
     *
     * @mbg.generated
     */
    private BigDecimal longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.latitude
     *
     * @mbg.generated
     */
    private BigDecimal latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.register_time
     *
     * @mbg.generated
     */
    private Date registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.is_valid
     *
     * @mbg.generated
     */
    private Boolean isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.is_disabled
     *
     * @mbg.generated
     */
    private Boolean isDisabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.discription
     *
     * @mbg.generated
     */
    private String discription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_user.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_user
     *
     * @mbg.generated
     */
    public HmUser(Integer id, String loginName, String nickName, String password, String userToken, String headImg, String phone, String email, BigDecimal point, BigDecimal longitude, BigDecimal latitude, Date registerTime, Boolean isValid, Boolean isDisabled, String discription, String memo) {
        this.id = id;
        this.loginName = loginName;
        this.nickName = nickName;
        this.password = password;
        this.userToken = userToken;
        this.headImg = headImg;
        this.phone = phone;
        this.email = email;
        this.point = point;
        this.longitude = longitude;
        this.latitude = latitude;
        this.registerTime = registerTime;
        this.isValid = isValid;
        this.isDisabled = isDisabled;
        this.discription = discription;
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_user
     *
     * @mbg.generated
     */
    public HmUser() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.id
     *
     * @return the value of hm_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.id
     *
     * @param id the value for hm_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.login_name
     *
     * @return the value of hm_user.login_name
     *
     * @mbg.generated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.login_name
     *
     * @param loginName the value for hm_user.login_name
     *
     * @mbg.generated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.nick_name
     *
     * @return the value of hm_user.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.nick_name
     *
     * @param nickName the value for hm_user.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.password
     *
     * @return the value of hm_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.password
     *
     * @param password the value for hm_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.user_token
     *
     * @return the value of hm_user.user_token
     *
     * @mbg.generated
     */
    public String getUserToken() {
        return userToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.user_token
     *
     * @param userToken the value for hm_user.user_token
     *
     * @mbg.generated
     */
    public void setUserToken(String userToken) {
        this.userToken = userToken == null ? null : userToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.head_img
     *
     * @return the value of hm_user.head_img
     *
     * @mbg.generated
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.head_img
     *
     * @param headImg the value for hm_user.head_img
     *
     * @mbg.generated
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg == null ? null : headImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.phone
     *
     * @return the value of hm_user.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.phone
     *
     * @param phone the value for hm_user.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.email
     *
     * @return the value of hm_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.email
     *
     * @param email the value for hm_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.point
     *
     * @return the value of hm_user.point
     *
     * @mbg.generated
     */
    public BigDecimal getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.point
     *
     * @param point the value for hm_user.point
     *
     * @mbg.generated
     */
    public void setPoint(BigDecimal point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.longitude
     *
     * @return the value of hm_user.longitude
     *
     * @mbg.generated
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.longitude
     *
     * @param longitude the value for hm_user.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.latitude
     *
     * @return the value of hm_user.latitude
     *
     * @mbg.generated
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.latitude
     *
     * @param latitude the value for hm_user.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.register_time
     *
     * @return the value of hm_user.register_time
     *
     * @mbg.generated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.register_time
     *
     * @param registerTime the value for hm_user.register_time
     *
     * @mbg.generated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.is_valid
     *
     * @return the value of hm_user.is_valid
     *
     * @mbg.generated
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.is_valid
     *
     * @param isValid the value for hm_user.is_valid
     *
     * @mbg.generated
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.is_disabled
     *
     * @return the value of hm_user.is_disabled
     *
     * @mbg.generated
     */
    public Boolean getIsDisabled() {
        return isDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.is_disabled
     *
     * @param isDisabled the value for hm_user.is_disabled
     *
     * @mbg.generated
     */
    public void setIsDisabled(Boolean isDisabled) {
        this.isDisabled = isDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.discription
     *
     * @return the value of hm_user.discription
     *
     * @mbg.generated
     */
    public String getDiscription() {
        return discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.discription
     *
     * @param discription the value for hm_user.discription
     *
     * @mbg.generated
     */
    public void setDiscription(String discription) {
        this.discription = discription == null ? null : discription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_user.memo
     *
     * @return the value of hm_user.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_user.memo
     *
     * @param memo the value for hm_user.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}