package com.jason.dao;

import com.jason.model.HmUser;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface HmUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_user
     *
     * @mbg.generated
     */
    @Delete({
            "delete from hm_user",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_user
     *
     * @mbg.generated
     */
    @Insert({
            "insert into hm_user (id, login_name, ",
            "nick_name, password, ",
            "user_token, head_img, ",
            "phone, email, point, ",
            "longitude, latitude, ",
            "register_time, is_valid, ",
            "is_disabled, discription, ",
            "memo)",
            "values (#{id,jdbcType=INTEGER}, #{loginName,jdbcType=VARCHAR}, ",
            "#{nickName,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
            "#{userToken,jdbcType=VARCHAR}, #{headImg,jdbcType=VARCHAR}, ",
            "#{phone,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, #{point,jdbcType=DECIMAL}, ",
            "#{longitude,jdbcType=DECIMAL}, #{latitude,jdbcType=DECIMAL}, ",
            "#{registerTime,jdbcType=TIMESTAMP}, #{isValid,jdbcType=BIT}, ",
            "#{isDisabled,jdbcType=BIT}, #{discription,jdbcType=VARCHAR}, ",
            "#{memo,jdbcType=VARCHAR})"
    })
    int insert(HmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_user
     *
     * @mbg.generated
     */
    int insertSelective(HmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_user
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "id, login_name, nick_name, password, user_token, head_img, phone, email, point, ",
            "longitude, latitude, register_time, is_valid, is_disabled, discription, memo",
            "from hm_user",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.jason.dao.HmUserMapper.BaseResultMap")
    HmUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_user
     *
     * @mbg.generated
     */
    @Update({
            "update hm_user",
            "set login_name = #{loginName,jdbcType=VARCHAR},",
            "nick_name = #{nickName,jdbcType=VARCHAR},",
            "password = #{password,jdbcType=VARCHAR},",
            "user_token = #{userToken,jdbcType=VARCHAR},",
            "head_img = #{headImg,jdbcType=VARCHAR},",
            "phone = #{phone,jdbcType=VARCHAR},",
            "email = #{email,jdbcType=VARCHAR},",
            "point = #{point,jdbcType=DECIMAL},",
            "longitude = #{longitude,jdbcType=DECIMAL},",
            "latitude = #{latitude,jdbcType=DECIMAL},",
            "register_time = #{registerTime,jdbcType=TIMESTAMP},",
            "is_valid = #{isValid,jdbcType=BIT},",
            "is_disabled = #{isDisabled,jdbcType=BIT},",
            "discription = #{discription,jdbcType=VARCHAR},",
            "memo = #{memo,jdbcType=VARCHAR}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(HmUser record);
}