package com.jason.dao;

import com.jason.model.Room;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface RoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    @Delete({
            "delete from room",
            "where room_id = #{roomId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    @Insert({
            "insert into room (room_id, create_time, ",
            "creater)",
            "values (#{roomId,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
            "#{creater,jdbcType=VARCHAR})"
    })
    int insert(Room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    int insertSelective(Room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "room_id, create_time, creater",
            "from room",
            "where room_id = #{roomId,jdbcType=VARCHAR}"
    })
    @ResultMap("com.jason.dao.RoomMapper.BaseResultMap")
    Room selectByPrimaryKey(String roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    @Update({
            "update room",
            "set create_time = #{createTime,jdbcType=TIMESTAMP},",
            "creater = #{creater,jdbcType=VARCHAR}",
            "where room_id = #{roomId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Room record);
}