package com.jason.dao;

import com.jason.model.User;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Delete({
            "delete from user",
            "where user_id = #{userId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Insert({
            "insert into user (user_id, user_name, ",
            "nick_name, password, ",
            "last_login_time, register_time, ",
            "avatar, is_valid)",
            "values (#{userId,jdbcType=VARCHAR}, #{userName,jdbcType=VARCHAR}, ",
            "#{nickName,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
            "#{lastLoginTime,jdbcType=TIMESTAMP}, #{registerTime,jdbcType=TIMESTAMP}, ",
            "#{avatar,jdbcType=VARCHAR}, #{isValid,jdbcType=BIT})"
    })
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "user_id, user_name, nick_name, password, last_login_time, register_time, avatar, ",
            "is_valid",
            "from user",
            "where user_id = #{userId,jdbcType=VARCHAR}"
    })
    @ResultMap("com.jason.dao.UserMapper.BaseResultMap")
    User selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Update({
            "update user",
            "set user_name = #{userName,jdbcType=VARCHAR},",
            "nick_name = #{nickName,jdbcType=VARCHAR},",
            "password = #{password,jdbcType=VARCHAR},",
            "last_login_time = #{lastLoginTime,jdbcType=TIMESTAMP},",
            "register_time = #{registerTime,jdbcType=TIMESTAMP},",
            "avatar = #{avatar,jdbcType=VARCHAR},",
            "is_valid = #{isValid,jdbcType=BIT}",
            "where user_id = #{userId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(User record);
}